products = [
    {
        "_id": 1,
        "name": "AirPods Wireless Bluetooth Headphones",
        "image": "/images/airpods.jpg",
        "description":
        "AirPods are wireless Bluetooth earbuds designed by Apple Inc. They were first announced on September 7, 2016 alongside the iPhone 7.",
        "brand": "Apple",
        "category": "Electronics",
        "price": 89.99,
        "countInStock": 10,
        "rating": 4.5,
        "numReviews": 12,
    },
    {
        "_id": 2,
        "name": "Iphone 11 Pro 256GB Memory",
        "image": "/images/iphone.jpeg",
        "description":
        "iPhone 11 Pro mobile was launched on 10th September 2019. The phone comes with a 5.80-inch touchscreen display offering a resolution of 1125x2436 pixels at a pixel density of 458 pixels per inch (ppi). iPhone 11 Pro is powered by a hexa-core Apple A13 Bionic processor. It comes with 4GB of RAM.",
        "brand": "Apple",
        "category": "Electronics",
        "price": 599.99,
        "countInStock": 0,
        "rating": 4.0,
        "numReviews": 8,
    },
    {
        "_id": 3,
        "name": "Cannon EOS 80D DSLR Camera",
        "image": "/images/camera.jpeg",
        "description":
        "The EOS 80D camera features a newly developed 24.2 Megapixel (APS-C) CMOS sensor that not only captures high-resolution images, but also features refined individual pixels that enable high ISO speeds of 16000 for still photographs (expandable to 25600) and 12800 for movies (expandable to 16000, 25600).",
        "brand": "Cannon",
        "category": "Electronics",
        "price": 929.99,
        "countInStock": 5,
        "rating": 3,
        "numReviews": 12,
    },
    {
        "_id": 4,
        "name": "Sony Playstation 4 Pro White Version",
        "image": "/images/playstation.jpeg",
        "description":
        "An excellent all-round console with a fantastic catalog of AAA games, the slimmed down PS4 is better in almost every way compared to the original – barring one notable exception.",
        "brand": "Sony",
        "category": "Electronics",
        "price": 399.99,
        "countInStock": 11,
        "rating": 5,
        "numReviews": 12,
    },
    {
        "_id": 5,
        "name": "Logitech G-Series Gaming Mouse",
        "image": "/images/mouse.jpeg",
        "description":
        "An excellent all-round console with a fantastic catalog of AAA games, the slimmed down PS4 is better in almost every way compared to the original – barring one notable exception.",
        "brand": "Logitech",
        "category": "Electronics",
        "price": 49.99,
        "countInStock": 7,
        "rating": 3.5,
        "numReviews": 10,
    },
    {
        "_id": 6,
        "name": "Amazon Echo Dot 3rd Generation",
        "image": "/images/alexa.jpeg",
        "description":
        "An excellent all-round console with a fantastic catalog of AAA games, the slimmed down PS4 is better in almost every way compared to the original – barring one notable exception.",
        "brand": "Logitech",
        "category": "Electronics",
        "price": 29.99,
        "countInStock": 0,
        "rating": 4,
        "numReviews": 12,
    },
]
